import ActionForm from '@/components/ActionForm';
import PageHead from '@/components/PageHead';
import StatusBadge from '@/components/StatusBadge';
import db from '@/lib/db';
import { today, shortDate } from '@/lib/utils';
import { addTask, deleteTask, updateTaskStatus } from '@/app/actions';

const taskStatuses = ['Pending','In Progress','Completed','Hold'];
export default async function Tasks({searchParams}:{searchParams:Promise<{month?:string;status?:string}>}) {
  const sp=await searchParams; const month=/^\d{4}-\d{2}$/.test(sp.month||'') ? sp.month! : today().slice(0,7); const status=sp.status||'';
  const clients=(await db.prepare('SELECT id,name FROM clients ORDER BY name').all()) as any[];
  let sql=`SELECT t.*,c.name client_name FROM tasks t LEFT JOIN clients c ON c.id=t.client_id WHERE substr(t.task_date,1,7)=?`; const args:any[]=[month];
  if(status){sql+=' AND t.status=?';args.push(status);} sql+=' ORDER BY date(t.task_date),t.id DESC';
  const rows=(await db.prepare(sql).all(...args)) as any[];
  const counts=(await db.prepare(`SELECT status,COUNT(*) count FROM tasks WHERE substr(task_date,1,7)=? GROUP BY status`).all(month)) as any[]; const count=(s:string)=>Number(counts.find(x=>x.status===s)?.count||0);
  const [year,mon]=month.split('-').map(Number); const days=new Date(year,mon,0).getDate(); const perDay=new Map<number,any[]>(); rows.forEach(r=>{const d=Number(String(r.task_date).slice(8,10));perDay.set(d,[...(perDay.get(d)||[]),r]);});
  return <><PageHead title="Realtime Task Board" subtitle="Add daily work, move tasks between statuses and review the whole month." />
    <div className="kpis">{taskStatuses.map(s=><div className="card kpi" key={s}><div className="kpi-top"><span>{s}</span></div><div className="kpi-value">{count(s)}</div></div>)}</div>
    <section className="card card-pad form-card"><h3 className="section-title">Add Task</h3><ActionForm action={addTask} style={{marginTop:16}}><div className="form-grid"><div className="field"><label>Task *</label><input className="input" name="title" required /></div><div className="field"><label>Client</label><select className="select" name="client_id"><option value="">General task</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="field"><label>Date *</label><input className="input" type="date" name="task_date" defaultValue={today()} required /></div><div className="field"><label>Priority</label><select className="select" name="priority"><option>Low</option><option>Normal</option><option>High</option><option>Urgent</option></select></div><div className="field"><label>Status</label><select className="select" name="status">{taskStatuses.map(s=><option key={s}>{s}</option>)}</select></div><div className="field span2"><label>Description</label><textarea className="textarea" name="description" /></div></div><div className="form-actions"><button className="btn btn-primary">Add Task</button></div></ActionForm></section>
    <form className="filters" style={{marginTop:18}}><input className="input" style={{maxWidth:220}} type="month" name="month" defaultValue={month}/><select className="select" style={{maxWidth:180}} name="status" defaultValue={status}><option value="">All statuses</option>{taskStatuses.map(s=><option key={s}>{s}</option>)}</select><button className="btn">Filter</button></form>
    <section className="card"><div className="section-head"><h3 className="section-title">Daily Calendar · {month}</h3></div><div className="table-wrap"><table className="table"><thead><tr>{Array.from({length:7},(_,i)=><th key={i}>{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][i]}</th>)}</tr></thead><tbody>{Array.from({length:Math.ceil((days+new Date(year,mon-1,1).getDay())/7)},(_,week)=><tr key={week}>{Array.from({length:7},(_,dow)=>{const day=week*7+dow-new Date(year,mon-1,1).getDay()+1; const dayRows=day>=1&&day<=days?(perDay.get(day)||[]):[];return <td key={dow} style={{minWidth:150,height:110}}>{day>=1&&day<=days&&<><b>{String(day).padStart(2,'0')}</b>{dayRows.slice(0,3).map(r=><div key={r.id} className="small" style={{marginTop:6}}>{r.title} · {r.status}</div>)}{dayRows.length>3&&<div className="small muted">+{dayRows.length-3} more</div>}</>}</td>})}</tr>)}</tbody></table></div></section>
    <section className="card" style={{marginTop:18}}><div className="table-wrap"><table className="table"><thead><tr><th>Date</th><th>Task</th><th>Client</th><th>Priority</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{shortDate(r.task_date)}</td><td><b>{r.title}</b><div className="small muted">{r.description||''}</div></td><td>{r.client_name||'General'}</td><td>{r.priority}</td><td><StatusBadge value={r.status}/></td><td><ActionForm action={updateTaskStatus.bind(null,r.id)}><div className="actions"><select className="select" name="status" defaultValue={r.status}>{taskStatuses.map(s=><option key={s}>{s}</option>)}</select><button className="btn btn-sm btn-success">Update</button></div></ActionForm><ActionForm confirmMessage="Delete this task?" action={deleteTask.bind(null,r.id)}><button className="btn btn-sm btn-danger" style={{marginTop:6}}>Delete</button></ActionForm></td></tr>)}{!rows.length&&<tr><td colSpan={6}><div className="empty">No tasks for this month.</div></td></tr>}</tbody></table></div></section>
  </>;
}
